on:
  push:
    branches:
      - '*'

jobs:
  verify:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install libdbus-1-dev
      - run: cargo clippy
      - run: cargo test
